import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class MusicService {
  constructor(
    private readonly httpService: HttpService,
    private readonly configService: ConfigService,
  ) {}

  async generatePlaylist(quadrant: string, spotifyAccessToken: string): Promise<string> {
    // Step 1: Map mood to seed artists
    const seedArtists = this.moodToSeedArtists(quadrant);

    // Step 2: Discover similar artists via Last.fm
    const similarArtists = await this.discoverSimilarArtists(seedArtists);

    // Step 3: Search Spotify for tracks by these artists
    const trackUris = await this.searchSpotifyTracks(similarArtists, spotifyAccessToken);

    // Step 4: Get Spotify user ID
    const meResp = await this.httpService.axiosRef.get('https://api.spotify.com/v1/me', {
      headers: { Authorization: `Bearer ${spotifyAccessToken}` },
    });
    const spotifyUserId = meResp.data.id;

    // Step 5: Create playlist
    const playlistName = `Unravel: ${this.quadrantToLabel(quadrant)}`;
    const playlistResp = await this.httpService.axiosRef.post(
      `https://api.spotify.com/v1/users/${spotifyUserId}/playlists`,
      { name: playlistName, description: 'Generated by Unravel', public: false },
      { headers: { Authorization: `Bearer ${spotifyAccessToken}` } },
    );

    // Step 6: Add tracks
    if (trackUris.length > 0) {
      await this.httpService.axiosRef.post(
        `https://api.spotify.com/v1/playlists/${playlistResp.data.id}/tracks`,
        { uris: trackUris.slice(0, 30) },
        { headers: { Authorization: `Bearer ${spotifyAccessToken}` } },
      );
    }

    return playlistResp.data.external_urls.spotify;
  }

  private moodToSeedArtists(quadrant: string): string[] {
    const mapping: Record<string, string[]> = {
      highEnergyPleasant: ['Pharrell Williams', 'Dua Lipa', 'Bruno Mars'],
      highEnergyUnpleasant: ['Linkin Park', 'Rage Against the Machine', 'Eminem'],
      lowEnergyUnpleasant: ['Radiohead', 'Bon Iver', 'Elliott Smith'],
      lowEnergyPleasant: ['Norah Jones', 'Jack Johnson', 'Iron & Wine'],
    };
    return mapping[quadrant] ?? mapping['lowEnergyPleasant'];
  }

  private quadrantToLabel(quadrant: string): string {
    const labels: Record<string, string> = {
      highEnergyPleasant: 'Joyful Energy',
      highEnergyUnpleasant: 'Intense Release',
      lowEnergyUnpleasant: 'Quiet Reflection',
      lowEnergyPleasant: 'Serene Calm',
    };
    return labels[quadrant] ?? 'Mood Mix';
  }

  private async discoverSimilarArtists(seedArtists: string[]): Promise<string[]> {
    const lastFmKey = this.configService.get<string>('LASTFM_API_KEY');
    const similarArtists: string[] = [];

    for (const artist of seedArtists) {
      try {
        const resp = await this.httpService.axiosRef.get(
          `https://ws.audioscrobbler.com/2.0/`, {
            params: {
              method: 'artist.getsimilar',
              artist,
              api_key: lastFmKey,
              format: 'json',
              limit: 5,
            },
          },
        );
        const artists = resp.data?.similarartists?.artist ?? [];
        similarArtists.push(...artists.map((a: any) => a.name));
      } catch {
        // Skip failed lookups
      }
    }

    return [...new Set(similarArtists)].slice(0, 15);
  }

  private async searchSpotifyTracks(artists: string[], token: string): Promise<string[]> {
    const trackUris: string[] = [];

    for (const artist of artists) {
      try {
        const resp = await this.httpService.axiosRef.get(
          'https://api.spotify.com/v1/search', {
            params: { q: `artist:${artist}`, type: 'track', limit: 2 },
            headers: { Authorization: `Bearer ${token}` },
          },
        );
        const tracks = resp.data?.tracks?.items ?? [];
        trackUris.push(...tracks.map((t: any) => t.uri));
      } catch {
        // Skip failed searches
      }
    }

    return trackUris;
  }
}
