/// The four quadrants of Russell's Circumplex Model of Affect.
enum MoodQuadrant {
  highEnergyPleasant, // Q1 – top-right (yellow)
  highEnergyUnpleasant, // Q2 – top-left (red)
  lowEnergyUnpleasant, // Q3 – bottom-left (blue)
  lowEnergyPleasant, // Q4 – bottom-right (green)
}

/// A single emotion word placed on the circumplex.
class EmotionWord {
  final String label;
  final MoodQuadrant quadrant;

  /// Pleasantness axis: -1.0 (unpleasant) to 1.0 (pleasant).
  final double valence;

  /// Energy axis: -1.0 (low energy) to 1.0 (high energy).
  final double arousal;

  const EmotionWord({
    required this.label,
    required this.quadrant,
    required this.valence,
    required this.arousal,
  });
}

/// 144 emotion words – 36 per quadrant.
const List<EmotionWord> circumplexEmotions = [
  // ── Q1: High Energy Pleasant (valence > 0, arousal > 0) ──────────────
  EmotionWord(label: 'Excited', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.80, arousal: 0.90),
  EmotionWord(label: 'Elated', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.85, arousal: 0.85),
  EmotionWord(label: 'Joyful', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.90, arousal: 0.70),
  EmotionWord(label: 'Euphoric', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.95, arousal: 0.95),
  EmotionWord(label: 'Energized', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.60, arousal: 0.90),
  EmotionWord(label: 'Thrilled', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.85, arousal: 0.92),
  EmotionWord(label: 'Ecstatic', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.95, arousal: 0.98),
  EmotionWord(label: 'Enthusiastic', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.75, arousal: 0.80),
  EmotionWord(label: 'Proud', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.70, arousal: 0.60),
  EmotionWord(label: 'Inspired', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.80, arousal: 0.65),
  EmotionWord(label: 'Amused', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.70, arousal: 0.55),
  EmotionWord(label: 'Delighted', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.88, arousal: 0.72),
  EmotionWord(label: 'Cheerful', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.75, arousal: 0.60),
  EmotionWord(label: 'Optimistic', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.70, arousal: 0.50),
  EmotionWord(label: 'Playful', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.72, arousal: 0.75),
  EmotionWord(label: 'Lively', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.65, arousal: 0.82),
  EmotionWord(label: 'Exhilarated', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.90, arousal: 0.93),
  EmotionWord(label: 'Confident', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.68, arousal: 0.55),
  EmotionWord(label: 'Passionate', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.82, arousal: 0.88),
  EmotionWord(label: 'Victorious', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.88, arousal: 0.80),
  EmotionWord(label: 'Amazed', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.78, arousal: 0.85),
  EmotionWord(label: 'Empowered', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.75, arousal: 0.70),
  EmotionWord(label: 'Vibrant', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.80, arousal: 0.82),
  EmotionWord(label: 'Eager', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.65, arousal: 0.78),
  EmotionWord(label: 'Hopeful', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.72, arousal: 0.48),
  EmotionWord(label: 'Festive', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.82, arousal: 0.78),
  EmotionWord(label: 'Blissful', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.92, arousal: 0.60),
  EmotionWord(label: 'Radiant', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.85, arousal: 0.68),
  EmotionWord(label: 'Triumphant', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.90, arousal: 0.82),
  EmotionWord(label: 'Overjoyed', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.95, arousal: 0.88),
  EmotionWord(label: 'Motivated', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.68, arousal: 0.72),
  EmotionWord(label: 'Uplifted', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.78, arousal: 0.62),
  EmotionWord(label: 'Spirited', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.70, arousal: 0.76),
  EmotionWord(label: 'Exuberant', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.88, arousal: 0.90),
  EmotionWord(label: 'Grateful', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.80, arousal: 0.45),
  EmotionWord(label: 'Alive', quadrant: MoodQuadrant.highEnergyPleasant, valence: 0.75, arousal: 0.85),

  // ── Q2: High Energy Unpleasant (valence < 0, arousal > 0) ────────────
  EmotionWord(label: 'Angry', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.80, arousal: 0.85),
  EmotionWord(label: 'Anxious', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.65, arousal: 0.80),
  EmotionWord(label: 'Stressed', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.70, arousal: 0.78),
  EmotionWord(label: 'Frustrated', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.72, arousal: 0.75),
  EmotionWord(label: 'Panicked', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.85, arousal: 0.95),
  EmotionWord(label: 'Tense', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.60, arousal: 0.72),
  EmotionWord(label: 'Irritated', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.62, arousal: 0.65),
  EmotionWord(label: 'Enraged', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.95, arousal: 0.98),
  EmotionWord(label: 'Furious', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.90, arousal: 0.95),
  EmotionWord(label: 'Nervous', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.55, arousal: 0.70),
  EmotionWord(label: 'Agitated', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.68, arousal: 0.82),
  EmotionWord(label: 'Overwhelmed', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.75, arousal: 0.80),
  EmotionWord(label: 'Hostile', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.88, arousal: 0.85),
  EmotionWord(label: 'Afraid', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.78, arousal: 0.82),
  EmotionWord(label: 'Terrified', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.92, arousal: 0.95),
  EmotionWord(label: 'Apprehensive', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.50, arousal: 0.60),
  EmotionWord(label: 'Alarmed', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.72, arousal: 0.88),
  EmotionWord(label: 'Distressed', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.78, arousal: 0.75),
  EmotionWord(label: 'Resentful', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.70, arousal: 0.58),
  EmotionWord(label: 'Jealous', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.65, arousal: 0.62),
  EmotionWord(label: 'Bitter', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.72, arousal: 0.55),
  EmotionWord(label: 'Worried', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.58, arousal: 0.65),
  EmotionWord(label: 'Defensive', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.55, arousal: 0.68),
  EmotionWord(label: 'Impatient', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.48, arousal: 0.60),
  EmotionWord(label: 'Restless', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.45, arousal: 0.72),
  EmotionWord(label: 'Uneasy', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.52, arousal: 0.58),
  EmotionWord(label: 'Horrified', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.90, arousal: 0.92),
  EmotionWord(label: 'Outraged', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.88, arousal: 0.90),
  EmotionWord(label: 'Exasperated', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.68, arousal: 0.72),
  EmotionWord(label: 'Frantic', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.82, arousal: 0.92),
  EmotionWord(label: 'Infuriated', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.92, arousal: 0.95),
  EmotionWord(label: 'Provoked', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.62, arousal: 0.70),
  EmotionWord(label: 'Rattled', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.58, arousal: 0.75),
  EmotionWord(label: 'Turbulent', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.70, arousal: 0.80),
  EmotionWord(label: 'Vengeful', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.85, arousal: 0.78),
  EmotionWord(label: 'Livid', quadrant: MoodQuadrant.highEnergyUnpleasant, valence: -0.92, arousal: 0.92),

  // ── Q3: Low Energy Unpleasant (valence < 0, arousal < 0) ─────────────
  EmotionWord(label: 'Sad', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.75, arousal: -0.55),
  EmotionWord(label: 'Depressed', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.90, arousal: -0.80),
  EmotionWord(label: 'Exhausted', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.65, arousal: -0.90),
  EmotionWord(label: 'Lonely', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.80, arousal: -0.60),
  EmotionWord(label: 'Hopeless', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.92, arousal: -0.75),
  EmotionWord(label: 'Apathetic', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.55, arousal: -0.85),
  EmotionWord(label: 'Drained', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.60, arousal: -0.88),
  EmotionWord(label: 'Bored', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.40, arousal: -0.70),
  EmotionWord(label: 'Melancholy', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.72, arousal: -0.55),
  EmotionWord(label: 'Gloomy', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.68, arousal: -0.60),
  EmotionWord(label: 'Miserable', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.88, arousal: -0.65),
  EmotionWord(label: 'Numb', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.50, arousal: -0.90),
  EmotionWord(label: 'Empty', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.70, arousal: -0.82),
  EmotionWord(label: 'Defeated', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.82, arousal: -0.70),
  EmotionWord(label: 'Helpless', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.85, arousal: -0.72),
  EmotionWord(label: 'Despondent', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.88, arousal: -0.78),
  EmotionWord(label: 'Fatigued', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.50, arousal: -0.85),
  EmotionWord(label: 'Lethargic', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.45, arousal: -0.88),
  EmotionWord(label: 'Withdrawn', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.60, arousal: -0.68),
  EmotionWord(label: 'Disheartened', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.75, arousal: -0.58),
  EmotionWord(label: 'Dismayed', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.70, arousal: -0.50),
  EmotionWord(label: 'Disappointed', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.65, arousal: -0.45),
  EmotionWord(label: 'Guilty', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.72, arousal: -0.48),
  EmotionWord(label: 'Ashamed', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.78, arousal: -0.52),
  EmotionWord(label: 'Regretful', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.68, arousal: -0.50),
  EmotionWord(label: 'Pessimistic', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.62, arousal: -0.55),
  EmotionWord(label: 'Powerless', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.80, arousal: -0.75),
  EmotionWord(label: 'Grief-stricken', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.92, arousal: -0.62),
  EmotionWord(label: 'Desolate', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.90, arousal: -0.78),
  EmotionWord(label: 'Sluggish', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.42, arousal: -0.82),
  EmotionWord(label: 'Weary', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.55, arousal: -0.78),
  EmotionWord(label: 'Forlorn', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.82, arousal: -0.65),
  EmotionWord(label: 'Dismal', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.75, arousal: -0.62),
  EmotionWord(label: 'Heartbroken', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.92, arousal: -0.55),
  EmotionWord(label: 'Isolated', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.72, arousal: -0.68),
  EmotionWord(label: 'Vulnerable', quadrant: MoodQuadrant.lowEnergyUnpleasant, valence: -0.58, arousal: -0.55),

  // ── Q4: Low Energy Pleasant (valence > 0, arousal < 0) ───────────────
  EmotionWord(label: 'Calm', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.75, arousal: -0.70),
  EmotionWord(label: 'Serene', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.82, arousal: -0.75),
  EmotionWord(label: 'Content', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.78, arousal: -0.55),
  EmotionWord(label: 'Relaxed', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.72, arousal: -0.72),
  EmotionWord(label: 'Peaceful', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.85, arousal: -0.78),
  EmotionWord(label: 'Grateful', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.80, arousal: -0.45),
  EmotionWord(label: 'Comfortable', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.70, arousal: -0.65),
  EmotionWord(label: 'Satisfied', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.75, arousal: -0.50),
  EmotionWord(label: 'Tranquil', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.80, arousal: -0.80),
  EmotionWord(label: 'Mellow', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.60, arousal: -0.72),
  EmotionWord(label: 'At Ease', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.72, arousal: -0.68),
  EmotionWord(label: 'Soothed', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.68, arousal: -0.70),
  EmotionWord(label: 'Safe', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.70, arousal: -0.60),
  EmotionWord(label: 'Cozy', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.72, arousal: -0.68),
  EmotionWord(label: 'Restful', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.65, arousal: -0.80),
  EmotionWord(label: 'Gentle', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.62, arousal: -0.65),
  EmotionWord(label: 'Thoughtful', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.55, arousal: -0.50),
  EmotionWord(label: 'Tender', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.65, arousal: -0.55),
  EmotionWord(label: 'Accepting', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.68, arousal: -0.52),
  EmotionWord(label: 'Balanced', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.60, arousal: -0.48),
  EmotionWord(label: 'Harmonious', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.75, arousal: -0.60),
  EmotionWord(label: 'Centered', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.65, arousal: -0.58),
  EmotionWord(label: 'Secure', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.72, arousal: -0.55),
  EmotionWord(label: 'Refreshed', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.68, arousal: -0.42),
  EmotionWord(label: 'Warm', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.70, arousal: -0.50),
  EmotionWord(label: 'Blessed', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.82, arousal: -0.48),
  EmotionWord(label: 'Grounded', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.62, arousal: -0.62),
  EmotionWord(label: 'Fulfilled', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.85, arousal: -0.45),
  EmotionWord(label: 'Mindful', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.58, arousal: -0.55),
  EmotionWord(label: 'Loved', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.90, arousal: -0.42),
  EmotionWord(label: 'Compassionate', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.72, arousal: -0.48),
  EmotionWord(label: 'Still', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.55, arousal: -0.82),
  EmotionWord(label: 'Rested', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.65, arousal: -0.75),
  EmotionWord(label: 'Relieved', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.70, arousal: -0.48),
  EmotionWord(label: 'Sleepy', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.40, arousal: -0.88),
  EmotionWord(label: 'Meditative', quadrant: MoodQuadrant.lowEnergyPleasant, valence: 0.60, arousal: -0.78),
];
